{
    'name': 'Prudential Module',
    'version': '16.0.1.0.0',
    'category': 'Accounting',
    'summary': """ This modules is developed by prudential tech""",
    'description': """This modules enables approval feature in the payment. """,
    'author': ' Byasi Solomon',
    'company': 'Prudential Tech',
    'maintainer': 'Prudential Tech',
    'website': "",
    'depends': ['base', 'account', 'sale_management', 'purchase', 'stock', 'mrp'],
    'data': [
        'security/ir.model.access.csv',
        'views/account_payment_view.xml',
        'views/config_settings_view.xml',
        'views/purchase_view.xml',
        'views/purchase_config_settings_view.xml',
        'views/stock_picking_views.xml',
        'views/mrp_production-views.xml',
        'views/stock_move_views.xml',
        'views/stock_lot_views.xml',
        'views/stock_move_line_views.xml',
        'views/account_payment_register_views.xml',
        'views/sale_order_views.xml',
        'views/account_move_views.xml',
        'wizard/unfixed_price_view.xml',
        'views/general_report_wizard_view.xml',
        'views/general_report_menu.xml',
        'views/cashbook_report_wizard_view.xml',
        'views/cashbook_report_menu.xml',
        'report/general_report_pdf_template.xml',
        'report/general_report_pdf_action.xml',
        'report/cashbook_report_pdf_template.xml',
        'report/cashbook_report_pdf_action.xml',
        'report/payment_voucher_template.xml',
        'report/payment_voucher_action.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'sales_move/static/src/xml/list_controller.xml',
            'sales_move/static/src/js/list_controller.js',
        ],
    },
    'license': 'LGPL-3',
    'images': ['static/description/banner.png'],
    'installable': True,
    'auto_install': False,
    'application': True,
}
